apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: gatherspace
data:
  NODE_ENV: production
  MONGODB_URI: mongodb://mongodb:27017/GatherSpace
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: gatherspace
type: Opaque
data:
  # Default JWT secret (for development only)
  JWT_SECRET: YWhzYW5mYXJhejE3 # 'ahsanfaraz17' in base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: gatherspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ahsanfaraz/gatherspace-server:latest
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NODE_ENV
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: gatherspace
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: server
