name: Docker Login and Build Test
on:
  workflow_dispatch:

jobs:
  docker-login-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Try direct Docker login
        run: |
          # First test with username and password directly
          # Replace this with your actual password when testing
          docker login -u ahsanfaraz -p wajidhassan

          # Check login status
          if ($?) {
            echo "Direct login successful"
          } else {
            echo "Direct login failed - check credentials"
            exit 1
          }

      - name: Build simple test image
        run: |
          # Create a simple Dockerfile for testing
          @"
          FROM alpine:latest
          CMD ["echo", "Hello World"]
          "@ | Out-File -FilePath ./test.Dockerfile -Encoding ASCII

          # Build a test image
          docker build -t ahsanfaraz/test-image:latest -f ./test.Dockerfile .

          # Check if build was successful
          if ($?) {
            echo "Build successful"
          } else {
            echo "Build failed"
            exit 1
          }

      - name: Push test image
        run: |
          # Try to push the test image
          docker push ahsanfaraz/test-image:latest

          # Check if push was successful
          if ($?) {
            echo "Push successful"
          } else {
            echo "Push failed"
            exit 1
          }
