name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        run: |
          minikube start --driver=docker

      - name: Set up Docker to use Minikube's environment
        run: |
          echo "Configuring Docker to use Minikube's daemon..."
          minikube docker-env | Invoke-Expression

      - name: Login to Docker Hub
        run: |
          # Login to Docker Hub with direct credentials
          docker login -u ahsanfaraz -p wajidhassan

      - name: Build Client Docker image
        working-directory: ./app/client
        run: |
          docker build -t ahsanfaraz/gatherspace-client:latest .

      - name: Build Server Docker image
        working-directory: ./app/server
        run: |
          docker build -t ahsanfaraz/gatherspace-server:latest .

      - name: Push Docker images to Docker Hub
        run: |
          docker push ahsanfaraz/gatherspace-client:latest
          docker push ahsanfaraz/gatherspace-server:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f kubernetes/namespace.yaml
          kubectl apply -f kubernetes/mongodb.yaml
          kubectl apply -f kubernetes/backend.yaml
          kubectl apply -f kubernetes/frontend.yaml
          kubectl rollout status -n gatherspace deployment/client
          kubectl rollout status -n gatherspace deployment/server
